name: hola mundo

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "*/5 * * * *" # Se ejecuta cada 5 minutos
  # push:
  #   branches:
  #     - master

jobs:
  saludar:
    runs-on: ubuntu-latest
    steps:
      - name: Muentra mensaje hola mundo
        run: echo "Hola mundo, Yover"
